from . import workshop_equipo
from . import workshop_bay
from . import workshop_vehicle
from . import workshop_vehicle_owner_history
from . import workshop_inspection
from . import appointment_type
from . import calendar_event
from . import res_partner
from . import crm_lead
from . import sale_order
from . import sale_order_line
